
export const fullComprehensiveDrugsDatabase = [
  {
    id: "med-001",
    name: "Acetaminophen",
    nameVi: "Paracetamol",
    genericName: "Acetaminophen",
    genericNameVi: "Paracetamol",
    category: "Pain Reliever",
    categoryVi: "Thuốc giảm đau",
    primaryUse: "Pain relief and fever reduction",
    primaryUseVi: "Giảm đau và hạ sốt",
    adultDosage: "500-1000mg every 4-6 hours",
    adultDosageVi: "500-1000mg mỗi 4-6 giờ",
    maxDosage: "4000mg per day",
    maxDosageVi: "4000mg mỗi ngày",
    warnings: ["Do not exceed 4000mg daily", "Avoid alcohol"],
    warningsVi: ["Không vượt quá 4000mg mỗi ngày", "Tránh rượu"],
    createdAt: new Date().toISOString()
  },
  {
    id: "med-002",
    name: "Ibuprofen",
    nameVi: "Ibuprofen",
    genericName: "Ibuprofen",
    genericNameVi: "Ibuprofen",
    category: "NSAID",
    categoryVi: "Thuốc chống viêm",
    primaryUse: "Pain, inflammation, and fever relief",
    primaryUseVi: "Giảm đau, chống viêm và hạ sốt",
    adultDosage: "200-400mg every 4-6 hours",
    adultDosageVi: "200-400mg mỗi 4-6 giờ",
    maxDosage: "1200mg per day",
    maxDosageVi: "1200mg mỗi ngày",
    warnings: ["Take with food", "May cause stomach bleeding"],
    warningsVi: ["Uống cùng thức ăn", "Có thể gây xuất huyết dạ dày"],
    createdAt: new Date().toISOString()
  },
  {
    id: "med-003",
    name: "Mobic",
    nameVi: "Mobic",
    genericName: "Meloxicam",
    genericNameVi: "Meloxicam",
    category: "NSAID",
    categoryVi: "Thuốc chống viêm",
    primaryUse: "Arthritis pain and inflammation",
    primaryUseVi: "Đau khớp và viêm khớp",
    adultDosage: "7.5-15mg once daily",
    adultDosageVi: "7.5-15mg một lần mỗi ngày",
    maxDosage: "15mg per day",
    maxDosageVi: "15mg mỗi ngày",
    warnings: ["Take with food", "Monitor blood pressure"],
    warningsVi: ["Uống cùng thức ăn", "Theo dõi huyết áp"],
    createdAt: new Date().toISOString()
  },
  {
    id: "med-004",
    name: "Aspirin",
    nameVi: "Aspirin",
    genericName: "Acetylsalicylic Acid",
    genericNameVi: "Acid Acetylsalicylic",
    category: "NSAID",
    categoryVi: "Thuốc chống viêm",
    primaryUse: "Pain relief and blood thinner",
    primaryUseVi: "Giảm đau và chống đông máu",
    adultDosage: "325-650mg every 4 hours",
    adultDosageVi: "325-650mg mỗi 4 giờ",
    maxDosage: "4000mg per day",
    maxDosageVi: "4000mg mỗi ngày",
    warnings: ["Increases bleeding risk", "Not for children under 16"],
    warningsVi: ["Tăng nguy cơ chảy máu", "Không dành cho trẻ em dưới 16 tuổi"],
    createdAt: new Date().toISOString()
  },
  {
    id: "med-005",
    name: "Lisinopril",
    nameVi: "Lisinopril",
    genericName: "Lisinopril",
    genericNameVi: "Lisinopril",
    category: "ACE Inhibitor",
    categoryVi: "Thuốc ức chế ACE",
    primaryUse: "High blood pressure treatment",
    primaryUseVi: "Điều trị huyết áp cao",
    adultDosage: "5-40mg once daily",
    adultDosageVi: "5-40mg một lần mỗi ngày",
    maxDosage: "80mg per day",
    maxDosageVi: "80mg mỗi ngày",
    warnings: ["May cause dry cough", "Monitor kidney function"],
    warningsVi: ["Có thể gây ho khan", "Theo dõi chức năng thận"],
    createdAt: new Date().toISOString()
  }
];
